# Generated by Django 5.1.1 on 2024-11-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_smart', '0005_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contadordata',
            name='valor',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
